### ISSUE TITLE
Type Cast Issue 

### ISSUE THREAD

**Issue by SongOnWater** [ViewComfy/ViewComfy#30]
[wf.json](https://github.com/user-attachments/files/17606641/wf.json)
While I run this workflow on ViewComfy, it reports an error  "* ReActorFaceSwap 1:
  - Value not in list: console_log_level: '1' not in [0, 1, 2]" .  I did a little research and found that , the console_log_level value is  int type  , but when  sent to ComfyUI server , it was casted to string type.  Following is my resolution: 
  replace " obj[path[path.length - 1]] = input.value; "  in " setViewComfy(viewComfy: IInput[]) "  method with 
  "
 const value = isNaN(Number(input.value))
          ? input.value
          : Number(input.value);
        obj[path[path.length - 1]] = value; 
"

**Comment by LSliu666** [comment]
Hello, I still have the wrong type after correcting according to your instructions. Can you help me identify the problem? thank
@SongOnWater 
Loading base model ()...Done.
Removing last two layers (global_pool & classifier).
!!! Exception during processing!!! 'str' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/HD2T/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/HD2T/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/HD2T/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/HD2T/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dsine.py", line 22, in execute
    out = common_annotator_call(model, image, fov=fov, iterations=iterations, resolution=resolution)
  File "/HD2T/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 85, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
  File "/HD2T/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_controlnet_aux/dsine/__init__.py", line 87, in __call__
    normal = self.model(input_image, intrins)
  File "/project-ssd/miniconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/project-ssd/miniconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/HD2T/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_controlnet_aux/dsine/models/dsine_arch.py", line 226, in forward
    for i in range(self.num_iter):
TypeError: 'str' object cannot be interpreted as an integer

**Comment by chinchaun** [comment]
hey @SongOnWater, thanks for reporting this, I manage to reproduce it and have a fix to push.

`
Value not in list: console_log_level: '1' not in [0, 1, 2]" . I did a little research and found that , the console_log_level value is int type , but when sent to ComfyUI server , it was casted to string type
`
The problem here is that we send a FormData to the backend and the only values that class support is string or File, so when we get that data in the backend it only represents those 2 values.

**Comment by chinchaun** [comment]
hey @SongOnWater, thanks for reporting this, I manage to reproduce it and have a fix to push.

`
Value not in list: console_log_level: '1' not in [0, 1, 2]" . I did a little research and found that , the console_log_level value is int type , but when sent to ComfyUI server , it was casted to string type
`
The problem here is that we send a FormData to the backend and the only values that class support are string or File, so when we get that data in the backend it only represents those 2 values.
